/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8c10fa3394f6350119cee13044544cb9)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	CONTACT_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
