/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f9ca05787c84afe716e9dabeb58b0284)
interface __BaseEnv_Env {
	CONTACT_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
