import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("builds the personal site as a complete static document", async () => {
  const html = await readFile(new URL("../dist/client/index.html", import.meta.url), "utf8");
  assert.match(html, /<title>JK de Guzman \| A personal field guide<\/title>/i);
  assert.match(html, /A person is a <em>collection<\/em> of connections\./i);
  assert.match(html, /Language/i);
  assert.match(html, /Systems/i);
  assert.match(html, /CliftonStrengths/i);
  assert.match(html, /November 21 · Scorpio/i);
  assert.match(html, /world-canvas/i);
  assert.match(html, /signal-visual/i);
  assert.match(html, /readable-zone/i);
  assert.match(html, /<script type="module" src="\/_astro\/[^\"]+\.js"><\/script>/i);
  assert.doesNotMatch(html, / style=/i);
  assert.match(html, /Nothing Phone \(3\)/i);
  assert.match(html, /CMF Buds Pro 2/i);
  assert.match(html, /Fedora Kinoite/i);
  assert.match(html, /Windows 95/i);
  assert.match(html, /taught English online since 2019/i);
  assert.match(html, /Podman/i);
  assert.match(html, /contact-form/i);
  assert.match(html, /data-action="turnstile-spin-v2"/i);
  assert.match(html, /challenges\.cloudflare\.com\/turnstile\/v0\/api\.js/i);
  assert.match(html, /Country or territory/i);
  assert.match(html, /Want a reply\? Leave an email or mobile number/i);
  assert.match(html, /stack-trace-step/i);
  assert.match(html, /Philippines/i);
  assert.doesNotMatch(html, /Marikina|1988|depression|stroke survivor|Losartan|amlodipine/i);
  const emailPattern = /\b[\w.%+-]+@[\w.-]+\.[A-Z]{2,}\b/i;
  assert.doesNotMatch(html, emailPattern);
  assert.doesNotMatch(html, /mailto:/i);
  assert.match(html, /Skip to content/i);
  assert.match(html, /<html lang="en-US">/i);
  assert.match(html, /aria-label="Primary navigation"/i);
  assert.match(html, /href="#strengths"/i);
  assert.match(html, /href="#details"/i);
  assert.match(html, /001 \/ 008/i);
  assert.match(html, /data-callback="iamjkTurnstileReady"/i);
  assert.match(html, /data-expired-callback="iamjkTurnstileExpired"/i);
  assert.match(html, /data-error-callback="iamjkTurnstileError"/i);
  assert.doesNotMatch(html, /No funnel|No pitch deck|Build a life with enough substance|No single <span>lane/i);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|SkeletonPreview/i);

  const source = await readFile(new URL("../src/pages/index.astro", import.meta.url), "utf8");
  assert.match(source, /requestAnimationFrame/i);
  assert.match(source, /import \{ gsap \} from "gsap"/i);
  assert.match(source, /import \{ ScrollTrigger \} from "gsap\/ScrollTrigger"/i);
  assert.match(source, /gsap\.matchMedia\(\)/i);
  assert.match(source, /gsap\.registerPlugin\(ScrollTrigger\)/i);
  assert.match(source, /iamjkTurnstileExpired/i);
  assert.match(source, /__iamjkTurnstileState/i);
  assert.match(source, /prefers-reduced-motion/i);
  assert.match(source, /DETAIL/);
  assert.match(source, /const focusY = height \* 0\.46/);
  assert.match(source, /bounds\.top <= focusY && bounds\.bottom >= focusY/);
  assert.match(source, /const nearestIndex = focusIndex >= 0 \? focusIndex : visibleIndex/);
  assert.match(source, /let sectionStateDirty = true/);
  assert.match(source, /if \(sections\.length === 0 \|\| !sectionStateDirty\) return/);
  assert.match(source, /sectionStateDirty = true/);
  assert.match(source, /const maxPixelRatio = width < 700 \? 1\.5 : 2/);
  assert.match(source, /let pageVisible = !document\.hidden/);
  assert.match(source, /if \(!pageVisible \|\| animationFrameId !== 0 \|\| motionQuery\.matches\) return/);
  assert.match(source, /if \(motionQuery\.matches\) return/);
  assert.match(source, /motionQuery\.addEventListener\("change"/);
  assert.match(source, /document\.addEventListener\("visibilitychange"/);
  assert.match(source, /data-world-readout="ABOUT"/);
  assert.match(source, /data-world-detail="A LITTLE CONTEXT"/);
  assert.match(source, /const readoutNumber = section\?\.dataset\.worldIndex/);
  assert.match(source, /const readoutTitle = section\?\.dataset\.worldReadout/);
  assert.match(source, /turnstileSiteKey/);
  assert.match(source, /Replace with the public Site Key for the `whoisjk-me` Turnstile widget/);
  assert.match(html, /whoisjk\.me \/ a personal field guide/i);
  assert.match(source, /\/api\/contact/);
  assert.match(source, /Content-Type.*application.json/);
  assert.doesNotMatch(source, /TURNSTILE_SECRET_VALUE|RESEND_API_KEY_VALUE/);

  const endpoint = await readFile(new URL("../src/pages/api/contact.ts", import.meta.url), "utf8");
  assert.match(endpoint, /siteverify/);
  assert.match(endpoint, /result\.success === true/);
  assert.match(endpoint, /whoisjk-me-contact/);
  assert.match(endpoint, /idempotency-key/);
  assert.match(endpoint, /requestId/);
  assert.match(endpoint, /CONTACT_RATE_LIMITER\.limit/);
  assert.match(endpoint, /cf-connecting-ip/);
  assert.match(endpoint, /origin !==/);
  assert.match(endpoint, /https:\/\/whoisjk\.me/);
  assert.match(endpoint, /result\.hostname === "whoisjk\.me"/);
  assert.match(endpoint, /subject: .*whoisjk\.me/);
  assert.match(endpoint, /application/);
  assert.doesNotMatch(endpoint, /website@iamjk\.site|hello@iamjk\.site/);

  const middleware = await readFile(new URL("../src/middleware.ts", import.meta.url), "utf8");
  assert.match(middleware, /Content-Security-Policy/);
  assert.match(middleware, /private, no-store/);
  assert.match(middleware, /Strict-Transport-Security/);

  const staticHeaders = await readFile(new URL("../public/_headers", import.meta.url), "utf8");
  assert.match(staticHeaders, /Content-Security-Policy/);
  assert.match(staticHeaders, /X-Frame-Options: DENY/);

  const astroConfig = await readFile(new URL("../astro.config.mjs", import.meta.url), "utf8");
  assert.match(astroConfig, /checkOrigin:\s*true/);

  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.match(css, /--accent:\s*#c8844a/i);
  assert.match(css, /fallback-orbit/i);
  assert.match(css, /trace-flow/i);
  assert.match(css, /\.contact-form/);
  assert.match(css, /\.cf-turnstile/);
  assert.match(css, /min-height:\s*44px/);
  assert.match(css, /\.scroll-progress/);
  assert.match(css, /min-height:\s*48px/);
  assert.doesNotMatch(css, /@keyframes scene-wave[^}]*margin-left:/i);
  assert.match(css, /\.process-list li:last-child\s*\{\s*border-bottom:\s*0/i);
  assert.doesNotMatch(css, /\.card-number\s*\{[^}]*margin-bottom:\s*auto/i);
  assert.match(css, /\.card-arrow\s*\{[^}]*margin-top:\s*auto/i);
  assert.doesNotMatch(css, /box-shadow|backdrop-filter|shadowBlur|filter:\s*blur/i);
  assert.doesNotMatch(css, /@keyframes scene-device-float[^}]*translate:\s/i);
  assert.match(css, /\.world-readout\s*\{\s*display:\s*none/i);
  assert.doesNotMatch(css, /violet|purple|8052ff|7543ff|9b68ff/i);

  const caddy = await readFile(new URL("../deploy/Caddyfile.example", import.meta.url), "utf8");
  assert.match(caddy, /header_up Host \{host\}/i);
  assert.match(caddy, /Strict-Transport-Security/i);
  assert.match(caddy, /Cross-Origin-Resource-Policy/i);
  assert.match(caddy, /path \/api\/\*/i);
  assert.match(caddy, /CDN-Cache-Control "no-store"/i);
  assert.match(caddy, /Cache-Control "private, no-store"/i);
  assert.match(caddy, /request_body @iamjk_api/i);
  assert.match(caddy, /max_size 16KB/i);
  assert.doesNotMatch(caddy, /Cache-Control "public, max-age=/i);
  assert.doesNotMatch(caddy, /root \* \/srv\/iamjk-site|file_server/i);

  const quadlet = await readFile(new URL("../deploy/iamjk-site.container.example", import.meta.url), "utf8");
  assert.match(quadlet, /DropCapability=all/);

  const deployment = await readFile(new URL("../scripts/deploy-vps.sh", import.meta.url), "utf8");
  assert.match(deployment, /VPS deployment is retired: this project now deploys to Cloudflare Workers/);
  assert.match(deployment, /CLOUDFLARE_WORKERS_DEPLOYMENT\.md/);
  assert.doesNotMatch(deployment, /rsync|podman|systemctl|ssh/);

  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  const security = await readFile(new URL("../SECURITY.md", import.meta.url), "utf8");
  assert.doesNotMatch(`${readme}\n${security}`, /website@iamjk\.site|hello@iamjk\.site/);

  const favicon = await readFile(new URL("../public/favicon.svg", import.meta.url), "utf8");
  assert.match(favicon, /#050505/i);
  assert.match(favicon, /#F4F2EF/i);
  assert.doesNotMatch(favicon, /68C4FF|0C79D8|2E9EFF/i);
});
